### ISSUE TITLE
info, err := u.GetList("/foo")当 /foo 文件夹为空时，运行直接报错

### ISSUE THREAD

**Issue by ArronYR** [upyun/go-sdk#8]
```
// Get dir info list 
info, err := u.GetList("/foo")
```
当 `/foo` 文件夹为空时，运行直接报错:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/upyun/go-sdk/upyun.newInfo(0x436bf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/arron/Documents/go_workspace/src/github.com/upyun/go-sdk/upyun/upyun.go:164 +0x189
github.com/upyun/go-sdk/upyun.(*UpYun).GetList(0xc208054060, 0x2d9170, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/arron/Documents/go_workspace/src/github.com/upyun/go-sdk/upyun/upyun.go:450 +0x254
main.main()
	/Users/arron/Documents/go_workspace/src/go_upyun/go_upyun.go:29 +0x453

goroutine 8 [select]:
net/http.(*persistConn).readLoop(0xc2080680b0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc2080680b0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc208010610, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010610, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080105b0, 0xc208059000, 0x1000, 0x1000, 0x0, 0x1011b08, 0xc20800af40)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c0b0, 0xc208059000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x1012e18, 0xc20802c0b0, 0xc208068268, 0xc208059000, 0x1000, 0x1000, 0xc20802a2c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801eb00, 0xc208059000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208054cc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208054cc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208068210)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc208068210)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
exit status 2
```

**Comment by yejingx** [comment]
fixed #10
